In [1]:
from _utils import *

In [ ]:
raw_json_df = pd.read_json(JSON_FP)
annotations_df = pd.read_excel(ANNOTATIONaS_FP)

HTTP_ERROR_LIST = raw_json_df.query("error_code.notna()")[["row_id"]]["row_id"].tolist()
INNA_ERROR_LIST = annotations_df.query("subtype_1 == 'Exclude - Not on Model DB'")[["row_id"]]["row_id"].tolist()
a = set(HTTP_ERROR_LIST)
b = set(INNA_ERROR_LIST)

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

In [13]:
#Things in my list that aren't online
EXTRA_ERRORS = list(b-a)
View(raw_json_df.query("row_id in @EXTRA_ERRORS")[["url"]])

                                                                                  url
121      https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/ExIAF.mod
245      https://modeldb.science/230811?tab=2&file=PapoutsiEtAl2017/mod_files/cad.mod
596              https://modeldb.science/151460?tab=2&file=MiocinovicEtAl2006/KDR.mod
960     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/InhIAF.mod
1007  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSom.mod
1021     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/PACEF.MOD
1025  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSyn.mod
1168  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasInp.mod

In [12]:
View(raw_json_df.query("has_include == 1")[["url"]].reset_index(drop=True))

                                                                                 url
0   https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod
1                        https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod
2                        https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod
3            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inak.mod
4                       https://modeldb.science/9889?tab=2&file=lytton97/GABALOW.mod
5                         https://modeldb.science/7399?tab=2&file=lytton98/GABAA.mod
6                         https://modeldb.science/136095?tab=2&file=ncdemo/NMDAr.mod
7                       https://modeldb.science/12631?tab=2&file=lytton97b/GABAA.mod
8                             https://modeldb.science/35358?tab=2&file=35358/cal.mod
9                       https://modeldb.science/12631?tab=2&file=lytton97b/pulse.mod
10                      https://modeldb.science/144490?tab=2&file=bpap/nmda_andr.mod
11              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kaolmkop.mod
12                  https://modeldb.science/37819?tab=2&file=thal_aug_resp/nstim.mod
13                       https://modeldb.science/84589?tab=2&file=eaps/mod/hsoma.mod
14                        https://modeldb.science/74298?tab=2&file=sth-model/HVA.mod
15                https://modeldb.science/182134?tab=2&file=hfo_model/mod/kahppr.mod
16                         https://modeldb.science/84589?tab=2&file=eaps/mod/cat.mod
17                         https://modeldb.science/9889?tab=2&file=lytton97/AMPA.mod
18            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/isi.mod
19                      https://modeldb.science/84589?tab=2&file=eaps/mod/kaprox.mod
20                        https://modeldb.science/136095?tab=2&file=ncdemo/AMPAr.mod
21                    https://modeldb.science/37819?tab=2&file=thal_aug_resp/kdr.mod
22              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kapyrkop.mod
23                         https://modeldb.science/84589?tab=2&file=eaps/mod/can.mod
24                     https://modeldb.science/12631?tab=2&file=lytton97b/pregen.mod
25                     https://modeldb.science/116859?tab=2&file=ctxnet_v7/GABAa.mod
26               https://modeldb.science/186768?tab=2&file=SanjayEtAl2015/iholmw.mod
27              https://modeldb.science/182134?tab=2&file=hfo_model/mod/iholmkop.mod
28                       https://modeldb.science/185858?tab=2&file=CaHDemo/ihlts.mod
29              https://modeldb.science/182134?tab=2&file=hfo_model/mod/ihpyrkop.mod
30                   https://modeldb.science/37819?tab=2&file=thal_aug_resp/AMPA.mod
31             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/if.mod
32        https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/cadynam.mod
33             https://modeldb.science/182134?tab=2&file=hfo_model/mod/nafolmkop.mod
34                       https://modeldb.science/9889?tab=2&file=lytton97/GABAB1.mod
35          https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inaca.mod
36                          https://modeldb.science/7400?tab=2&file=lytton99/kdr.mod
37            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/ibg.mod
38                   https://modeldb.science/64229?tab=2&file=netmod/parbush/nap.mod

In [10]:
from _utils import *

COMPILED_FOLDERS = [p.name for p in COMPILED_DIR.iterdir() if p.is_dir()]

In [37]:
raw_json_df = pd.read_json(JSON_FP)
MODEL_IDS = raw_json_df["model_id"].tolist()

In [13]:
a = set(COMPILED_FOLDERS)
b = set(MODEL_IDS)
len(b-a)

457

In [38]:
View(raw_json_df.query("has_include == 1"))

      row_id                                                         file_hash                                                           raw_sha  count                                                                               url  model_id             created_date                                                                                   download_url                                filename                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        content error_code  has_include                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                download_inc_url        download_date
9         10  a60a597677abbb4b755e0c0ecc6bc3ccb4a013bdcaba16ee4d9f81441399f4ec  9e58366f7bed865d583439908aaabb0522769e24f4d0650d4cbeb390a53ebdab      1  https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod    254217   2019-04-01T20:12:54.59  https://modeldb.science/getModelFile?model=254217&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod  GidonEtAl2020_fig3andS9/_mod/mySyn.mod                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \nCOMMENT\n\n\nUse only what is in ISyn and IUtils\n\nENDCOMMENT\n\nNEURON {\n\tPOINT_PROCESS mySyn\n}\n\nINCLUDE "ISyn.inc"\nINCLUDE "IUtils.inc"\n\nNET_RECEIVE(w) {\n\tEPSP(1): finally trigger an epsp\n}\n       None            1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/ISyn.inc, https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/IUtils.inc]  2025-10-26 13:34:20
17        18  d21365cb949fb3f9c01c652c39aa84262012e536ceb6c9d8dd6df678a3c8b168  3a8be119a84f08f064463d859c9dbc24f2bed23997ac8b3fb34521e114cc749c      1                       https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod    136095      2010-11-01T18:06:09                       https://modeldb.science/getModelFile?model=136095&file=ncdemo/GABAar.mod                       ncdemo/GABAar.mod                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NEURON {  POINT_PROCESS GABAar }\n\nPARAMETER {\n  Cdur\t= 1.08\t(ms)\t\t: transmitter duration (rising phase)\n  Alpha\t= 1.\t(/ms mM)\t: forward (binding) rate\n  Beta\t= 0.5\t(/ms)\t\t: backward (unbinding) rate\n  Erev\t= -70\t(mV)\t\t: reversal potential\n}\n\nINCLUDE "netrand.inc"\n \n:** GABAbr\n       None            1                                                                                                                                                                                                                                                                                                                                                                                                            [https://modeldb.science/136095?tab=2&file=ncdemo/bg_cvode.inc, https://modeldb.science/136095?tab=2&file=ncdemo/netcon.inc, https://modeldb.science/136095?tab=2&file=ncdemo/netrand.inc, https://modeldb.science/136095?tab=2&file=ncdemo/ofc.inc]  2025-10-26 13:34:21
23        24  fdc16c53e18ef0ba78daf28cd1b723a6be60296758de522259c570ace8a596ca  1d7f7d44476384604f7d1b5aa931914e72ce2e039d6b1375286ab7a8da961dae      1                       https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod     51022      2005-03-28T10:03:04                       https://modeldb.science/getModelFile?model=51022&file=amirdevor03/fh.mod                      amirdevor03/fh.mod                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TITLE FH channel\r\n: Frankenhaeuser - Huxley channels for Xenopus\r\n\r\nNEURON {\r\n\tSUFFIX fh\r\n\tUSEION na READ nai, nao WRITE ina\r\n\tUSEION k READ ki, ko WRITE ik\r\n\tNONSPECIFIC_CURRENT il, ip\r\n\tRANGE pnabar, pkbar, ppbar, gl, el, il, ip\r\n\tGLOBAL inf,tau\r\n}\r\n\r\nINCLUDE "standard.inc"\r\nPARAMETER {\r\n\tv (mV)\r\n\tcelsius (degC) : 20\r\n\tpnabar=8e-3 (cm/s)\r\n\tppbar=.54e-3 (cm/s)\r\n\tpkbar=1.2e-3 (cm/s)\r\n\tnai (mM) : 13.74\r\n\tnao (mM) : 114.5\r\n\tki (mM) : 120\r\n\tko (mM) : 2.5\r\n\tgl=30.3e-3 (mho/cm2)\r\n\tel = -69.74 (mV)\r\n}\r\nSTATE {\r\n\tm h n p\r\n}\r\nASSIGNED {\r\n\tina (mA/cm2)\r\n\tik (mA/cm2)\r\n\tip (mA/cm2)\r\n\til (mA/cm2)\r\n\tinf[4]\r\n\ttau[4] (ms)\r\n}\r\n\r\nINITIAL {\r\n\tmhnp(v*1(/mV))\r\n\tm = inf[0]\r\n\th = inf[1]\r\n\tn = inf[2]\r\n\tp = inf[3]\r\n}\r\n\r\nBREAKPOINT {\r\n\tLOCAL ghkna\r\n\tSOLVE states METHOD cnexp\r\n\tghkna = ghk(v, nai, nao)\r\n\tina = pnabar*m*m*h*ghkna\r\n\tip = ppbar*p*p*ghkna\r\n\tik = pkbar*n*n*ghk(v, ki, ko)\r\n\til = gl*(v - el)\r\n}\r\n\r\nFUNCTION ghk(v(mV), ci(mM), co(mM)) (.001 coul/cm3) {\r\n\t:assume a single charge\r\n\tLOCAL z, eci, eco\r\n\tz = (1e-3)*FARADAY*v/(R*(celsius+273.15))\r\n\teco = co*efun(z)\r\n\teci = ci*efun(-z)\r\n\tghk = (.001)*FARADAY*(eci - eco)\r\n}\r\n\r\nFUNCTION efun(z) {\r\n\tif (fabs(z) < 1e-4) {\r\n\t\tefun = 1 - z/2\r\n\t}else{\r\n\t\tefun = z/(exp(z) - 1)\r\n\t}\r\n}\r\n\r\nDERIVATIVE states {\t: exact when v held constant\r\n\tmhnp(v*1(/mV))\r\n\tm' = (inf[0] - m)/tau[0]\r\n\th' = (inf[1] - h)/tau[1]\r\n\tn' = (inf[2] - n)/tau[2]\r\n\tp' = (inf[3] - p)/tau[3]\r\n}\r\n\r\nUNITSOFF\r\nFUNCTION alp(v(mV),i) { LOCAL a,b,c,q10 :rest = -70  order m,h,n,p\r\n\tv = v+70\r\n\tq10 = 3^((celsius - 20)/10)\r\n\tif (i==0) {\r\n\t\ta=.36 b=22. c=3.\r\n\t\talp = q10*a*expM1(b - v, c)\r\n\t}else if (i==1){\r\n\t\ta=.1 b=-10. c=6.\r\n\t\talp = q10*a*expM1(v - b, c)\r\n\t}else if (i==2){\r\n\t\ta=.02 b= 35. c=10.\r\n\t\talp = q10*a*expM1(b - v, c)\r\n\t}else{\r\n\t\ta=.006 b= 40. c=10.\r\n\t\talp = q10*a*expM1(b - v , c)\r\n\t}\r\n}\r\n\r\nFUNCTION bet(v,i) { LOCAL a,b,c,q10 :rest = -70  order m,h,n,p\r\n\tv = v+70\r\n\tq10 = 3^((celsius - 20)/10)\r\n\tif (i==0) {\r\n\t\ta=.4  b= 13.  c=20.\r\n\t\tbet = q10*a*expM1(v - b, c)\r\n\t}else if (i==1){\r\n\t\ta=4.5  b= 45.  c=10.\r\n\t\tbet = q10*a/(exp((b - v)/c) + 1)\r\n\t}else if (i==2){\r\n\t\ta=.05  b= 10.  c=10.\r\n\t\tbet = q10*a*expM1(v - b, c)\r\n\t}else{\r\n\t\ta=.09 b= -25. c=20.\r\n\t\tbet = q10*a*expM1(v - b, c)\r\n\t}\r\n}\r\n\r\nFUNCTION expM1(x,y) {\r\n\tif (fabs(x/y) < 1e-6) {\r\n\t\texpM1 = y*(1 - x/y/2)\r\n\t}else{\r\n\t\texpM1 = x/(exp(x/y) - 1)\r\n\t}\r\n}\r\n\r\nPROCEDURE mhnp(v) {LOCAL a, b :rest = -70\r\n\tTABLE inf, tau DEPEND celsius FROM -100 TO 100 WITH 200\r\n\tFROM i=0 TO 3 {\r\n\t\ta = alp(v,i)  b=bet(v,i)\r\n\t\ttau[i] = 1/(a + b)\r\n\t\tinf[i] = a/(a + b)\r\n\t}\r\n}\r\nUNITSON\r\n       None            1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [https://modeldb.science/51022?tab=2&file=amirdevor03/standard.inc]  2025-10-26 13:34:22

In [29]:
raw_json_df.query("has_include == 1")

,row_id,file_hash,raw_sha,count,url,model_id,created_date,download_url,filename,content,error_code,has_include,download_date
9,10,a60a597677abbb4b755e0c0ecc6bc3ccb4a013bdcaba16...,9e58366f7bed865d583439908aaabb0522769e24f4d065...,1,https://modeldb.science/254217?tab=2&file=Gido...,254217,2019-04-01T20:12:54.59,https://modeldb.science/getModelFile?model=254...,GidonEtAl2020_fig3andS9/_mod/mySyn.mod,\nCOMMENT\n\n\nUse only what is in ISyn and IU...,None,1,2025-10-24 10:33:50
17,18,d21365cb949fb3f9c01c652c39aa84262012e536ceb6c9...,3a8be119a84f08f064463d859c9dbc24f2bed23997ac8b...,1,https://modeldb.science/136095?tab=2&file=ncde...,136095,2010-11-01T18:06:09,https://modeldb.science/getModelFile?model=136...,ncdemo/GABAar.mod,NEURON { POINT_PROCESS GABAar }\n\nPARAMETER ...,None,1,2025-10-24 10:33:51
23,24,fdc16c53e18ef0ba78daf28cd1b723a6be60296758de52...,1d7f7d44476384604f7d1b5aa931914e72ce2e039d6b13...,1,https://modeldb.science/51022?tab=2&file=amird...,51022,2005-03-28T10:03:04,https://modeldb.science/getModelFile?model=510...,amirdevor03/fh.mod,TITLE FH channel\r\n: Frankenhaeuser - Huxley ...,None,1,2025-10-24 10:33:52
112,113,4eab8a3cf38b5ebf6a412a5fc3ea967f50fe97268993a9...,708a414651fa47c04b304535361797b0ce5fca469f7a5f...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/inak.mod,TITLE Na+/K+ pump current\r\nCOMMENT\r\n\tmodi...,None,1,2025-10-24 10:34:04
130,131,aeaa32102ec4a98a08d51c98d6323d900b285b408cd83d...,b667bcf23164b2b0abd10e52e45201c52e87caf765a57f...,1,https://modeldb.science/9889?tab=2&file=lytton...,9889,2002-07-09T15:54:48,https://modeldb.science/getModelFile?model=988...,lytton97/GABALOW.mod,NEURON { POINT_PROCESS GABALOW }\n: GABA SY...,None,1,2025-10-24 10:34:06
144,145,470bf7bdf1af2732b1e95b6b804d183d3686b2b6d5ff1d...,6464120cd61f938abeb9ff0592d5f83b9cf7628b58d06f...,1,https://modeldb.science/7399?tab=2&file=lytton...,7399,2002-04-22T15:16:03,https://modeldb.science/getModelFile?model=739...,lytton98/GABAA.mod,NEURON { POINT_PROCESS GABAA }\n: GABA SYNA...,None,1,2025-10-24 10:34:08
147,148,4b45d21388eec84b52f561903cd021f441015f45c85e41...,41149457a4ac8bf219a506b30c1ccd489dced3ec2c3757...,1,https://modeldb.science/136095?tab=2&file=ncde...,136095,2010-11-01T18:06:09,https://modeldb.science/getModelFile?model=136...,ncdemo/NMDAr.mod,NEURON{ POINT_PROCESS NMDAr\n RANGE B \n GLO...,None,1,2025-10-24 10:34:08
148,149,c73b80f66376f8903f42dc702da273c3523a9087e20f74...,caa258dcdb18bb086c5b8603bbe7167b513070cc1c9524...,1,https://modeldb.science/12631?tab=2&file=lytto...,12631,2002-07-29T08:00:57,https://modeldb.science/getModelFile?model=126...,lytton97b/GABAA.mod,NEURON { POINT_PROCESS GABAA }\n: GABA SYNA...,None,1,2025-10-24 10:34:08
267,268,cf61cb0ac4b0e1ab5230b994e5701deea8540388630454...,1a3a593c8ba6907a83532d143adafffb08da43fdfae303...,1,https://modeldb.science/35358?tab=2&file=35358...,35358,2004-02-09T17:12:24,https://modeldb.science/getModelFile?model=353...,35358/cal.mod,NEURON { SUFFIX cal }\nNEURON { USEION ca WRIT...,None,1,2025-10-24 10:34:23
284,286,4375ed0f480cbe4572e4b30abcffe052bed63a65aa0265...,ff50fd3038727cc99c90938ade94903bf349d60e8a08c3...,1,https://modeldb.science/12631?tab=2&file=lytto...,12631,2002-07-29T08:00:57,https://modeldb.science/getModelFile?model=126...,lytton97b/pulse.mod,": $Id: pulse.mod,v 1.1 1998/07/21 13:54:10 bil...",None,1,2025-10-24 10:34:26
354,356,6c27633fce64e5c8c36038b5d1d72376f4e04abcea8990...,2d0197598c104c9388e785a068f0cb9930f36b56c9ce79...,1,https://modeldb.science/144490?tab=2&file=bpap...,144490,2012-04-27T10:06:31,https://modeldb.science/getModelFile?model=144...,bpap/nmda_andr.mod,COMMENT\n\nAMPA synapse with two decay time co...,None,1,2025-10-24 10:34:35
369,371,1e47dfd343d0bed6630ec508e86d32fe62dae51a242b97...,2f041f1a0619a67b7876760956aaf5a91f570fc3faa539...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kaolmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:34:36
379,381,0bc08be0d006feda991c15eb9281621209eb30e3d848f3...,438325dd4b4d1dc6439979e3ece8fbcea905f23d845006...,1,https://modeldb.science/37819?tab=2&file=thal_...,37819,2004-04-26T16:54:51,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/nstim.mod,": $Id: nstim.mod,v 1.5 2004/03/15 22:43:00 bil...",None,1,2025-10-24 10:34:38
492,494,3ad5b20f42e6f26a02dc46faca8b9cecb818086297eb45...,97f5a78aeccf32a7c237f49376fc7437343f1755bbfffb...,1,https://modeldb.science/84589?tab=2&file=eaps/...,84589,2007-01-21T16:24:05,https://modeldb.science/getModelFile?model=845...,eaps/mod/hsoma.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-24 10:34:52
498,500,69b9b260751b45969472fb5738ede4cccd302644ca34b2...,43f4d2e26d58a9017aa720cb13e96950a45a5ff9fd7b78...,1,https://modeldb.science/74298?tab=2&file=sth-m...,74298,2006-07-25T08:51:58,https://modeldb.science/getModelFile?model=742...,sth-model/HVA.mod,TITLE calcium HVA channels for STh\n\nCOMMENT\...,None,1,2025-10-24 10:34:53
521,523,7956137d31f76eee12d884bcb1e3c7f8400d03e687ac6b...,5fc3b0156b2e0e18269c0e26ae40ae407480948940de13...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kahppr.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:34:56
546,548,cc449c78632dd81ba77c27990d30bbbd428a1c840b9dd9...,5457e9cb365eb4282d46b8b2840a4bd2cb20f2483e9518...,1,https://modeldb.science/84589?tab=2&file=eaps/...,84589,2007-01-21T16:24:05,https://modeldb.science/getModelFile?model=845...,eaps/mod/cat.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-24 10:34:59
566,568,ecb18e2aee7f2e5e99d8a399446ddac7216b5d9fe2c67e...,87e3992133d25b553285f8c8bb83f4b6122cbaf651121f...,1,https://modeldb.science/9889?tab=2&file=lytton...,9889,2002-07-09T15:54:48,https://modeldb.science/getModelFile?model=988...,lytton97/AMPA.mod,NEURON { POINT_PROCESS AMPA }\n: GLUTAMAT...,None,1,2025-10-24 10:35:01
601,603,84adc8f66c540e937bf2bb0715d487ed2389ac3a2446db...,231363284fe84b49b2b325881e54456f91166024911e73...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/isi.mod,TITLE Cardiac second inward current\r\nCOMMENT...,None,1,2025-10-24 10:35:07
621,624,c079f94be2f92d61be6a10d2b1f011e2a6679964bb9271...,a128858296997500d88c862e3027013a562b3b903e424d...,1,https://modeldb.science/84589?tab=2&file=eaps/...,84589,2007-01-21T16:24:05,https://modeldb.science/getModelFile?model=845...,eaps/mod/kaprox.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-24 10:35:10
625,628,9c4f6f7a24fecca13895df07df6db72c6ce269ff5b0801...,63decbeaf382ff47652e5f2e3bc54b253e56fab9e1aa70...,1,https://modeldb.science/136095?tab=2&file=ncde...,136095,2010-11-01T18:06:09,https://modeldb.science/getModelFile?model=136...,ncdemo/AMPAr.mod,NEURON { POINT_PROCESS AMPAr }\n\nPARAMETER {...,None,1,2025-10-24 10:35:10
641,644,dc268641ef30ec45575a83f2c4826dee807d4edb395f0d...,2a539b2351e11ddde09fa29b8a976607012a3172356cc1...,1,https://modeldb.science/37819?tab=2&file=thal_...,37819,2004-04-26T16:54:51,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/kdr.mod,NEURON { SUFFIX kdr }\n \nNEURON { USEION k R...,None,1,2025-10-24 10:35:12
643,646,d66ae67e11d63dc9799cf2df8ec9cf5179a0439045f94e...,9c38d6cd8940be38929cd7f34df9ca66868b7ee429b471...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kapyrkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:35:12
717,720,9ec536878ec419509adc2dbe6a1927a40af875a98ed663...,90e02ad710ebe7263955e6cf7ef38826eeef037b203c61...,1,https://modeldb.science/84589?tab=2&file=eaps/...,84589,2007-01-21T16:24:05,https://modeldb.science/getModelFile?model=845...,eaps/mod/can.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-24 10:35:22
734,737,e4a9c80ab18cb727f83fdcddd39485d5c432115f1d128d...,22e3a964f26cae6fc7e77d11200ab36fbb5c06b1355a03...,2,https://modeldb.science/12631?tab=2&file=lytto...,12631,2002-07-29T08:00:57,https://modeldb.science/getModelFile?model=126...,lytton97b/pregen.mod,": $Id: pregen.mod,v 1.13 1996/04/07 16:18:19 b...",None,1,2025-10-24 10:35:24
824,827,e69c59be20a70ff0b00fe25d121d65f2a3862b425ca232...,3c43704feeb37505d1e63bf14af27291141d0434dddfdf...,2,https://modeldb.science/116859?tab=2&file=ctxn...,116859,2005-04-12T09:23:22,https://modeldb.science/getModelFile?model=116...,ctxnet_v7/GABAa.mod,NEURON { POINT_PROCESS GABAa }\n\nPARAMETER {...,None,1,2025-10-24 10:35:36
855,858,e48a8cc099e179a30038b3cd83950de3d9e13529f1c8b5...,2cd89524cdfc144e9d78403c61ad6df1423028044e64b1...,3,https://modeldb.science/186768?tab=2&file=Sanj...,186768,2015-12-15T05:30:33.34,https://modeldb.science/getModelFile?model=186...,SanjayEtAl2015/iholmw.mod,": $Id: iholmw.mod,v 1.2 2010/11/30 16:34:22 sa...",None,1,2025-10-24 10:35:40
857,860,3920669e8369dacfae16c6c774655993d4c7864a9c8eb0...,6e5ea7f0df96f3093231d02e9a4711f312f62614f079d9...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/iholmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:35:41
869,872,bb3423e0dd0807606fb68954ad8a0f159177a9bada5e2e...,a893a1897d9e5642c8eaa3ddf29ab0b687b9006a313f1c...,2,https://modeldb.science/185858?tab=2&file=CaHD...,185858,2015-11-20T09:44:57.707,https://modeldb.science/getModelFile?model=185...,CaHDemo/ihlts.mod,UNITS {\n (mA) = (milliamp)\n (mV) = (milliv...,None,1,2025-10-24 10:35:42
873,876,6c24d97a4b0a010e2cdbe9e6dd3ba7a60f01aff5cab03b...,ff384a3199f64d592943504fb0beb9d61df32575dca736...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/ihpyrkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:35:43
947,950,55e57d745221229394c3b22845c215e4a076ecbc137b2d...,dd5fedc713b1f2cfe2416c564cacf58dbe9239f149283f...,1,https://modeldb.science/37819?tab=2&file=thal_...,37819,2004-04-26T16:54:51,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/AMPA.mod,NEURON {POINT_PROCESS AMPA}\n\nPARAMETER {\n ...,None,1,2025-10-24 10:35:52
1014,1017,8bb1c0f7f5bb346ca4039684bf5f2c38402a398764edef...,8989ddc64224aa8d00a40b687303b872c0ba1aeb9d0559...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/if.mod,TITLE Sodium/Calcium Cardiac hyperpolarizing I...,None,1,2025-10-24 10:36:01
1023,1026,8d57b88e925ce7840ac0d48c09e7e551feffcbfb20b20f...,45f3ab1fde9608c99679aa9473c70e094f8550a51f4b3e...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/cadynam.mod,TITLE Cardiac intracellular calcium accumulati...,None,1,2025-10-24 10:36:02
1040,1043,d607448500d0851557f3aedbb2d58d35d22cba228d6dae...,6ac767728e0adfd4da71cd10f507a9b18fec0248baa6a4...,8,https://modeldb.science/182134?tab=2&file=hfo_...,182134,2015-05-07T11:15:53.127,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/nafolmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-24 10:36:04
1144,1102,e8c7fdfbc04565d7b0c7b81b2289cd390a25f170a6765b...,5c726c4aca4ef8ca421ddc443e54d9804dfbb970f704cc...,1,https://modeldb.science/9889?tab=2&file=lytton...,9889,2002-07-09T15:54:48,https://modeldb.science/getModelFile?model=988...,lytton97/GABAB1.mod,NEURON { POINT_PROCESS GABAB1 }\n: Simple s...,None,1,2025-10-24 10:36:18
1166,1169,635d09c4f23db4a4ad832e10b5aaa6eeaf518587d1ffc6...,4d54d933bb593b3dedc43a326d5772f0171b26a0256094...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/inaca.mod,TITLE sodium calcium exchange\r\nCOMMENT\r\n\t...,None,1,2025-10-24 10:36:21
1211,1214,898e0e497bbb8349f0ce0a13bcc02786b56929d66d5ce0...,9d8fb9eb77288795066e865cef495a77951565cb47136c...,2,https://modeldb.science/7400?tab=2&file=lytton...,7400,2002-04-22T15:23:46,https://modeldb.science/getModelFile?model=740...,lytton99/kdr.mod,NEURON { SUFFIX kdr }\n \nNEURON { USEION k W...,None,1,2025-10-24 10:36:27
1216,1219,1b08c84bf6c17499388206330bd3fa342725d452b1d9df...,de757e995a1c4ea3272db5fb36961a2999b85ca36668b9...,1,https://modeldb.science/144520?tab=2&file=DiFr...,144520,2012-06-07T17:58:39,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/ibg.mod,TITLE sodium Background Current\r\nCOMMENT\r\n...,None,1,2025-10-24 10:36:27
1236,1239,6832d2e765941d8f275cd645a2d427530e6440a117c489...,19512119e7989e88c6d321e5262acbcec26b425ac6ca99...,1,https://modeldb.science/64229?tab=2&file=netmo...,64229,2006-03-18T20:42:02,https://modeldb.science/getModelFile?model=642...,netmod/parbush/nap.mod,NEURON { SUFFIX nap }\nNEURON { USEION na WRIT...,None,1,2025-10-24 10:36:30

In [21]:
from _utils import *

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

Found 1297 annotated samples

Downloading MOD files:   3%|▎         | 40/1297 [00:02<01:32, 13.56it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/napRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/napRT03.mod

Downloading MOD files:   4%|▍         | 50/1297 [00:03<01:20, 15.56it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/napf.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/napf.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/it1.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/it1.mod

Downloading MOD files:   7%|▋         | 97/1297 [00:06<01:15, 15.80it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  11%|█         | 145/1297 [00:09<01:12, 15.78it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/intf.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/intf.mod

Downloading MOD files:  14%|█▍        | 187/1297 [00:12<01:10, 15.64it/s]

Error downloading https://modeldb.science/getModelFile?model=97882&file=TOM/klb2002/kx.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=97882&file=TOM/klb2002/kx.mod

Downloading MOD files:  16%|█▌        | 209/1297 [00:13<01:07, 16.17it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod

Downloading MOD files:  17%|█▋        | 221/1297 [00:14<01:06, 16.14it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/exp2syn_v2.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/exp2syn_v2.mod

Downloading MOD files:  23%|██▎       | 295/1297 [00:19<01:04, 15.53it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod

Downloading MOD files:  25%|██▌       | 327/1297 [00:21<01:07, 14.38it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod

Downloading MOD files:  27%|██▋       | 351/1297 [00:22<00:59, 15.97it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod

Downloading MOD files:  28%|██▊       | 357/1297 [00:23<00:59, 15.80it/s]

Error downloading https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/powerpc/nap.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/powerpc/nap.mod

Downloading MOD files:  30%|██▉       | 385/1297 [00:24<00:59, 15.26it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/rampsyn.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/rampsyn.mod

Downloading MOD files:  31%|███       | 401/1297 [00:26<01:01, 14.46it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/na3.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/na3.mod

Downloading MOD files:  32%|███▏      | 409/1297 [00:26<00:58, 15.08it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/pattern.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/pattern.mod

Downloading MOD files:  32%|███▏      | 415/1297 [00:26<00:56, 15.75it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/nafRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/nafRT03.mod
Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cal.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cal.mod

Downloading MOD files:  33%|███▎      | 423/1297 [00:27<00:55, 15.77it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kc.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kc.mod

Downloading MOD files:  34%|███▍      | 445/1297 [00:28<00:52, 16.11it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAlM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAlM95.mod

Downloading MOD files:  36%|███▌      | 461/1297 [00:29<00:51, 16.15it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cad.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cad.mod

Downloading MOD files:  36%|███▌      | 469/1297 [00:30<00:51, 16.07it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/na.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/na.mod

Downloading MOD files:  39%|███▊      | 500/1297 [00:32<00:46, 17.13it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=cahva_chan.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=cahva_chan.mod
Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  41%|████      | 530/1297 [00:34<00:51, 14.96it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/Mykca.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/Mykca.mod

Downloading MOD files:  43%|████▎     | 554/1297 [00:35<00:46, 16.07it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/AMPA16v8_noNetCon.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/AMPA16v8_noNetCon.mod

Downloading MOD files:  44%|████▍     | 570/1297 [00:36<00:45, 15.99it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/k2RT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/k2RT03.mod
Error downloading https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/pulses/pulsedistrib/ipulse2.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/pulses/pulsedistrib/ipulse2.mod

Downloading MOD files:  48%|████▊     | 622/1297 [00:40<00:43, 15.64it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/ar.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/ar.mod

Downloading MOD files:  51%|█████▏    | 667/1297 [00:43<00:36, 17.49it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  53%|█████▎    | 691/1297 [00:44<00:38, 15.82it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cacum.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cacum.mod

Downloading MOD files:  57%|█████▋    | 743/1297 [00:48<00:34, 15.97it/s]

Error downloading https://modeldb.science/getModelFile?model=97882&file=TOM/klb/h.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=97882&file=TOM/klb/h.mod

Downloading MOD files:  60%|█████▉    | 775/1297 [00:50<00:33, 15.77it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/cad.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/cad.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/hh3_flei.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/hh3_flei.mod

Downloading MOD files:  61%|██████    | 787/1297 [00:51<00:33, 15.27it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/iq.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/iq.mod

Downloading MOD files:  61%|██████    | 791/1297 [00:51<00:32, 15.80it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/kca.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/kca.mod

Downloading MOD files:  63%|██████▎   | 813/1297 [00:53<00:31, 15.26it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cat.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cat.mod

Downloading MOD files:  66%|██████▋   | 861/1297 [00:56<00:27, 15.83it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/borgkm.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/borgkm.mod

Downloading MOD files:  68%|██████▊   | 885/1297 [00:57<00:27, 15.16it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/NMDA_v6_3_opt.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/NMDA_v6_3_opt.mod

Downloading MOD files:  69%|██████▉   | 901/1297 [00:58<00:25, 15.48it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KdBG.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KdBG.mod

Downloading MOD files:  70%|███████   | 909/1297 [00:59<00:24, 15.69it/s]

Error downloading https://modeldb.science/getModelFile?model=156034&file=integration/Traub.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=156034&file=integration/Traub.mod
Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAtM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAtM95.mod

Downloading MOD files:  76%|███████▌  | 983/1297 [01:04<00:19, 15.88it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/h.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/h.mod

Downloading MOD files:  77%|███████▋  | 999/1297 [01:05<00:18, 16.05it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/arhRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/arhRT03.mod

Downloading MOD files:  80%|███████▉  | 1035/1297 [01:08<00:18, 14.49it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=Ka_chan.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=Ka_chan.mod

Downloading MOD files:  83%|████████▎ | 1081/1297 [01:10<00:13, 16.06it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cat.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cat.mod

Downloading MOD files:  84%|████████▍ | 1093/1297 [01:11<00:12, 16.03it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/vecst.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/vecst.mod
Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/kdrp.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/kdrp.mod

Downloading MOD files:  89%|████████▊ | 1151/1297 [01:15<00:09, 15.87it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/vecstim.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/vecstim.mod

Downloading MOD files:  90%|█████████ | 1169/1297 [01:16<00:07, 16.21it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KahpM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KahpM95.mod

Downloading MOD files:  92%|█████████▏| 1191/1297 [01:18<00:06, 15.63it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cad3.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cad3.mod

Downloading MOD files:  94%|█████████▎| 1213/1297 [01:19<00:05, 15.36it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp_slower.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp_slower.mod

Downloading MOD files:  96%|█████████▌| 1245/1297 [01:21<00:03, 15.61it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/My_cal.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/My_cal.mod

Downloading MOD files:  99%|█████████▉| 1286/1297 [01:24<00:00, 17.39it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files: 100%|██████████| 1297/1297 [01:24<00:00, 15.26it/s]

Total files processed: 1297, Successfully downloaded: 1243, Failed downloads: 54
Some downloads failed. Check log file: /nfs/roberts/project/pi_rm693/imc33/mod-annotation/logs/nmodl_download_errors_20251026_130849.log