In [1]:
from _utils import *

In [ ]:
raw_json_df = pd.read_json(JSON_FP)
annotations_df = pd.read_excel(ANNOTATIONaS_FP)

HTTP_ERROR_LIST = raw_json_df.query("error_code.notna()")[["row_id"]]["row_id"].tolist()
INNA_ERROR_LIST = annotations_df.query("subtype_1 == 'Exclude - Not on Model DB'")[["row_id"]]["row_id"].tolist()
a = set(HTTP_ERROR_LIST)
b = set(INNA_ERROR_LIST)

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

In [13]:
#Things in my list that aren't online
EXTRA_ERRORS = list(b-a)
View(raw_json_df.query("row_id in @EXTRA_ERRORS")[["url"]])

                                                                                  url
121      https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/ExIAF.mod
245      https://modeldb.science/230811?tab=2&file=PapoutsiEtAl2017/mod_files/cad.mod
596              https://modeldb.science/151460?tab=2&file=MiocinovicEtAl2006/KDR.mod
960     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/InhIAF.mod
1007  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSom.mod
1021     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/PACEF.MOD
1025  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSyn.mod
1168  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasInp.mod

In [12]:
View(raw_json_df.query("has_include == 1")[["url"]].reset_index(drop=True))

                                                                                 url
0   https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod
1                        https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod
2                        https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod
3            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inak.mod
4                       https://modeldb.science/9889?tab=2&file=lytton97/GABALOW.mod
5                         https://modeldb.science/7399?tab=2&file=lytton98/GABAA.mod
6                         https://modeldb.science/136095?tab=2&file=ncdemo/NMDAr.mod
7                       https://modeldb.science/12631?tab=2&file=lytton97b/GABAA.mod
8                             https://modeldb.science/35358?tab=2&file=35358/cal.mod
9                       https://modeldb.science/12631?tab=2&file=lytton97b/pulse.mod
10                      https://modeldb.science/144490?tab=2&file=bpap/nmda_andr.mod
11              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kaolmkop.mod
12                  https://modeldb.science/37819?tab=2&file=thal_aug_resp/nstim.mod
13                       https://modeldb.science/84589?tab=2&file=eaps/mod/hsoma.mod
14                        https://modeldb.science/74298?tab=2&file=sth-model/HVA.mod
15                https://modeldb.science/182134?tab=2&file=hfo_model/mod/kahppr.mod
16                         https://modeldb.science/84589?tab=2&file=eaps/mod/cat.mod
17                         https://modeldb.science/9889?tab=2&file=lytton97/AMPA.mod
18            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/isi.mod
19                      https://modeldb.science/84589?tab=2&file=eaps/mod/kaprox.mod
20                        https://modeldb.science/136095?tab=2&file=ncdemo/AMPAr.mod
21                    https://modeldb.science/37819?tab=2&file=thal_aug_resp/kdr.mod
22              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kapyrkop.mod
23                         https://modeldb.science/84589?tab=2&file=eaps/mod/can.mod
24                     https://modeldb.science/12631?tab=2&file=lytton97b/pregen.mod
25                     https://modeldb.science/116859?tab=2&file=ctxnet_v7/GABAa.mod
26               https://modeldb.science/186768?tab=2&file=SanjayEtAl2015/iholmw.mod
27              https://modeldb.science/182134?tab=2&file=hfo_model/mod/iholmkop.mod
28                       https://modeldb.science/185858?tab=2&file=CaHDemo/ihlts.mod
29              https://modeldb.science/182134?tab=2&file=hfo_model/mod/ihpyrkop.mod
30                   https://modeldb.science/37819?tab=2&file=thal_aug_resp/AMPA.mod
31             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/if.mod
32        https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/cadynam.mod
33             https://modeldb.science/182134?tab=2&file=hfo_model/mod/nafolmkop.mod
34                       https://modeldb.science/9889?tab=2&file=lytton97/GABAB1.mod
35          https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inaca.mod
36                          https://modeldb.science/7400?tab=2&file=lytton99/kdr.mod
37            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/ibg.mod
38                   https://modeldb.science/64229?tab=2&file=netmod/parbush/nap.mod

In [10]:
from _utils import *

COMPILED_FOLDERS = [p.name for p in COMPILED_DIR.iterdir() if p.is_dir()]

In [8]:
raw_json_df = pd.read_json(JSON_FP)
MODEL_IDS = raw_json_df["model_id"].tolist()

In [13]:
a = set(COMPILED_FOLDERS)
b = set(MODEL_IDS)
len(b-a)

457

In [21]:
from _utils import *

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

Found 1297 annotated samples

Downloading MOD files:   3%|▎         | 40/1297 [00:02<01:32, 13.56it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/napRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/napRT03.mod

Downloading MOD files:   4%|▍         | 50/1297 [00:03<01:20, 15.56it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/napf.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/napf.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/it1.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/it1.mod

Downloading MOD files:   7%|▋         | 97/1297 [00:06<01:15, 15.80it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  11%|█         | 145/1297 [00:09<01:12, 15.78it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/intf.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/intf.mod

Downloading MOD files:  14%|█▍        | 187/1297 [00:12<01:10, 15.64it/s]

Error downloading https://modeldb.science/getModelFile?model=97882&file=TOM/klb2002/kx.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=97882&file=TOM/klb2002/kx.mod

Downloading MOD files:  16%|█▌        | 209/1297 [00:13<01:07, 16.17it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod

Downloading MOD files:  17%|█▋        | 221/1297 [00:14<01:06, 16.14it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/exp2syn_v2.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/exp2syn_v2.mod

Downloading MOD files:  23%|██▎       | 295/1297 [00:19<01:04, 15.53it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=nacaexch.mod

Downloading MOD files:  25%|██▌       | 327/1297 [00:21<01:07, 14.38it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod

Downloading MOD files:  27%|██▋       | 351/1297 [00:22<00:59, 15.97it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/AMPA.mod

Downloading MOD files:  28%|██▊       | 357/1297 [00:23<00:59, 15.80it/s]

Error downloading https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/powerpc/nap.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/powerpc/nap.mod

Downloading MOD files:  30%|██▉       | 385/1297 [00:24<00:59, 15.26it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/rampsyn.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/rampsyn.mod

Downloading MOD files:  31%|███       | 401/1297 [00:26<01:01, 14.46it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/na3.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/na3.mod

Downloading MOD files:  32%|███▏      | 409/1297 [00:26<00:58, 15.08it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/pattern.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/pattern.mod

Downloading MOD files:  32%|███▏      | 415/1297 [00:26<00:56, 15.75it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/nafRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/nafRT03.mod
Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cal.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cal.mod

Downloading MOD files:  33%|███▎      | 423/1297 [00:27<00:55, 15.77it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kc.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kc.mod

Downloading MOD files:  34%|███▍      | 445/1297 [00:28<00:52, 16.11it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAlM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAlM95.mod

Downloading MOD files:  36%|███▌      | 461/1297 [00:29<00:51, 16.15it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cad.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cad.mod

Downloading MOD files:  36%|███▌      | 469/1297 [00:30<00:51, 16.07it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/na.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/na.mod

Downloading MOD files:  39%|███▊      | 500/1297 [00:32<00:46, 17.13it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=cahva_chan.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=cahva_chan.mod
Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  41%|████      | 530/1297 [00:34<00:51, 14.96it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/Mykca.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/Mykca.mod

Downloading MOD files:  43%|████▎     | 554/1297 [00:35<00:46, 16.07it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/AMPA16v8_noNetCon.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/AMPA16v8_noNetCon.mod

Downloading MOD files:  44%|████▍     | 570/1297 [00:36<00:45, 15.99it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/k2RT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/k2RT03.mod
Error downloading https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/pulses/pulsedistrib/ipulse2.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38240&file=CA1/mechanism/pulses/pulsedistrib/ipulse2.mod

Downloading MOD files:  48%|████▊     | 622/1297 [00:40<00:43, 15.64it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/ar.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/ar.mod

Downloading MOD files:  51%|█████▏    | 667/1297 [00:43<00:36, 17.49it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files:  53%|█████▎    | 691/1297 [00:44<00:38, 15.82it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cacum.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cacum.mod

Downloading MOD files:  57%|█████▋    | 743/1297 [00:48<00:34, 15.97it/s]

Error downloading https://modeldb.science/getModelFile?model=97882&file=TOM/klb/h.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=97882&file=TOM/klb/h.mod

Downloading MOD files:  60%|█████▉    | 775/1297 [00:50<00:33, 15.77it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/cad.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/cad.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/hh3_flei.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/hh3_flei.mod

Downloading MOD files:  61%|██████    | 787/1297 [00:51<00:33, 15.27it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/iq.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/iq.mod

Downloading MOD files:  61%|██████    | 791/1297 [00:51<00:32, 15.80it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/kca.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/kca.mod

Downloading MOD files:  63%|██████▎   | 813/1297 [00:53<00:31, 15.26it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cat.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cat.mod

Downloading MOD files:  66%|██████▋   | 861/1297 [00:56<00:27, 15.83it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp.mod
Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/borgkm.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/borgkm.mod

Downloading MOD files:  68%|██████▊   | 885/1297 [00:57<00:27, 15.16it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/NMDA_v6_3_opt.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/NMDA_v6_3_opt.mod

Downloading MOD files:  69%|██████▉   | 901/1297 [00:58<00:25, 15.48it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KdBG.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KdBG.mod

Downloading MOD files:  70%|███████   | 909/1297 [00:59<00:24, 15.69it/s]

Error downloading https://modeldb.science/getModelFile?model=156034&file=integration/Traub.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=156034&file=integration/Traub.mod
Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAtM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/CAtM95.mod

Downloading MOD files:  76%|███████▌  | 983/1297 [01:04<00:19, 15.88it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/h.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/h.mod

Downloading MOD files:  77%|███████▋  | 999/1297 [01:05<00:18, 16.05it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/arhRT03.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/arhRT03.mod

Downloading MOD files:  80%|███████▉  | 1035/1297 [01:08<00:18, 14.49it/s]

Error downloading https://modeldb.science/getModelFile?model=38229&file=Ka_chan.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38229&file=Ka_chan.mod

Downloading MOD files:  83%|████████▎ | 1081/1297 [01:10<00:13, 16.06it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cat.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/cat.mod

Downloading MOD files:  84%|████████▍ | 1093/1297 [01:11<00:12, 16.03it/s]

Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/vecst.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/vecst.mod
Error downloading https://modeldb.science/getModelFile?model=58173&file=b05oct26/kdrp.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=58173&file=b05oct26/kdrp.mod

Downloading MOD files:  89%|████████▊ | 1151/1297 [01:15<00:09, 15.87it/s]

Error downloading https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/vecstim.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=267103&file=%20LUTsyn_demo_files2/vecstim.mod

Downloading MOD files:  90%|█████████ | 1169/1297 [01:16<00:07, 16.21it/s]

Error downloading https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KahpM95.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=37970&file=ca3_2002/KahpM95.mod

Downloading MOD files:  92%|█████████▏| 1191/1297 [01:18<00:06, 15.63it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cad3.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/cad3.mod

Downloading MOD files:  94%|█████████▎| 1213/1297 [01:19<00:05, 15.36it/s]

Error downloading https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp_slower.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=65218&file=nrntraub/mod/kahp_slower.mod

Downloading MOD files:  96%|█████████▌| 1245/1297 [01:21<00:03, 15.61it/s]

Error downloading https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/My_cal.mod: 403 Client Error: Forbidden for url: https://modeldb.science/getModelFile?model=38241&file=CA1_multi/mechanism/not-currently-used/My_cal.mod

Downloading MOD files:  99%|█████████▉| 1286/1297 [01:24<00:00, 17.39it/s]

Error downloading None: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Downloading MOD files: 100%|██████████| 1297/1297 [01:24<00:00, 15.26it/s]

Total files processed: 1297, Successfully downloaded: 1243, Failed downloads: 54
Some downloads failed. Check log file: /nfs/roberts/project/pi_rm693/imc33/mod-annotation/logs/nmodl_download_errors_20251026_130849.log